# Generated by Django 4.2 on 2024-11-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('courseCode', models.CharField(choices=[('CS135', 'CS135'), ('MATH135', 'MATH135'), ('MATH137', 'MATH137'), ('COMMST223', 'COMMST223'), ('ECON101', 'ECON101')], max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('preftime', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Night', 'Night')], max_length=20)),
                ('personality', models.CharField(choices=[('Introvert', 'Introvert'), ('Extrovert', 'Extrovert')], max_length=20)),
                ('learning_style', models.CharField(choices=[('Audio', 'Audio'), ('Visual', 'Visual'), ('Kinaesthetic', 'Kinaesthetic')], max_length=20)),
            ],
        ),
    ]
