# Generated by Django 4.2 on 2024-11-21 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='courseCode',
            new_name='course_code',
        ),
    ]
